### ISSUE TITLE
Add 'result' information to the SearchResponse.

### ISSUE THREAD

**Issue by koushikGudla** [Constructor-io/constructorio-client-android#115]
`result` data comes back in the overall response JSON from the Search Results endpoint, however this data isn't parsed into the `SearchResponse` object. It contains information such as `page` and `num_results_per_page` which would be useful in the implementation of pagination. It would be great if `results` was parsed and at least the `page`, `num_results_per_page`, and `term` data was surfaced by the SDK. Thanks!

**Comment by jjl014** [comment]
This should be resolved in https://github.com/Constructor-io/constructorio-client-android/pull/117

Closing this issue. 👍
