### ISSUE TITLE
Request to Add a JSON String to the ResultData object of the SearchResponse

### ISSUE THREAD

**Issue by koushikGudla** [Constructor-io/constructorio-client-android#116]
when we trigger the `search` endpoint, we get a `SearchResponse` object back with a `rawdata` - JSON string(`that holds the entire search response content`) attached to it at this parent level. If I need to get any additional fields that are not parsed into the inner most object( `ResultData` ) of the `SearchResponse`, I need to get the full response JSON string present at the parent level, parse the entire response again at my end and utilize it. 

Instead, if we could have a JSON string(`that holds just the content of the ResultData not entire response`) added to the `ResultData` object of the `SearchResponse` would make things easier.

The iOS SDK does provide a [JSON object](https://constructor-io.github.io/constructorio-client-swift/Classes/CIOResult.html#/s:23ConstructorAutocomplete9CIOResultC4jsonSDySSypGvp) (`that holds just the content of the CIOResult not entire response`) in the inner `CIOResult` object of the `CIOSearchResponse` 

Can we have the same implemented on Android as well.

**Comment by jjl014** [comment]
Closing this as I believe this is no longer needed, but please let us know otherwise. Thanks!

**Comment by UADanielStorm** [comment]
Was resolved with https://github.com/Constructor-io/constructorio-client-android/pull/117 👍
